package:
  name: vscreenml_v2
  version: !!str 0.0.2

source:
  path: ./

build:
  preserve_egg_dir: True
  number: 0

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - rdkit
    - oddt
    - xgboost

about:
  home: https://github.com/gandrianov/VScreenML_v2
  license: MIT
  license_file: LICENSE
