package:
  name: vscreenml_v2
  version: !!str 0.0.1

source:
  path: ./

build:
  preserve_egg_dir: True
  number: 0

requirements:
  build:
    - python
    - setuptools
    # - oddt

  run:
    - python
    #- pyrosetta
    - rdkit
    - oddt

about:
  home: https://github.com/gandrianov/VScreenML_v2
  license: MIT
  license_file: LICENSE
